import PlayerControlHook from "@/components/actions/PlayerControlHook";
import PlayerCodeBlocks from "@/components/models/PlayerCodeBlocks";
import { Box } from "@chakra-ui/react";
// import PlayerControlEffects from "@/components/actions/PlayerControlEffects";
// import PlayerControls from "@/components/actions/PlayerControls";
// import PlayerStatsBoard from "@/components/models/PlayerStatsBoard";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>MADDEV RPG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w={"full"} h={"full"} style={{ backgroundColor: "black" }}>
        <div>
          <h1>Initialization</h1>
          <PlayerControlHook />
          <PlayerCodeBlocks />
        </div>
      </Box>
    </>
  );
}
